# -*- coding: utf-8 -*-
"""Weather data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1geNyZT3ozUQGQ6Y3ODjtKOow_KuJ13Hx
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import zipfile

path = "/content/"

# Unzip the uploaded file
zip_file_path = path + "Weather data.zip"
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(path)

temp = pd.read_csv(path+"temperature.csv")
hum = pd.read_csv(path+"humidity.csv")
pres = pd.read_csv(path+"pressure.csv")
wind_spd = pd.read_csv(path+"wind_speed.csv")
wind_dir = pd.read_csv(path+"wind_direction.csv")
desc = pd.read_csv(path+"weather_description.csv")
city_attr = pd.read_csv(path+"city_attributes.csv")

for df in [temp, hum, pres, wind_spd, wind_dir, desc]:
    df['datetime'] = pd.to_datetime(df['datetime'])

merged = temp.merge(hum, on="datetime", suffixes=("_temp", "_hum"))
merged = merged.merge(pres, on="datetime", suffixes=("", "_pres"))
merged = merged.merge(wind_spd, on="datetime", suffixes=("", "_windspd"))
merged = merged.merge(wind_dir, on="datetime", suffixes=("", "_winddir"))
merged = merged.merge(desc, on="datetime", suffixes=("", "_desc"))

merged.head()

merged["year"] = merged["datetime"].dt.year
merged["month"] = merged["datetime"].dt.month_name()
merged["hour"] = merged["datetime"].dt.hour

#Temperature Trend for One City (Example: New York)#
import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))
plt.plot(merged["datetime"], merged["New York"], label="Temperature (K)")
plt.title("New York Temperature Over Time")
plt.xlabel("Date")
plt.ylabel("Temperature (Kelvin)")
plt.legend()
plt.show()

#Humidity Trend Comparison Between 3 Cities
import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))
plt.plot(merged["datetime"], merged["New York_hum"], label="New York")
plt.plot(merged["datetime"], merged["Vancouver_hum"], label="Vancouver")
plt.plot(merged["datetime"], merged["Montreal_hum"], label="Montreal")
plt.title("Humidity Comparison Across Cities")
plt.ylabel("Humidity (%)")
plt.legend()
plt.show()

#Monthly Average Temperature
merged["month_num"] = merged["datetime"].dt.month

monthly_avg = merged.groupby("month_num")["New York"].mean()

monthly_avg.plot(kind='bar', figsize=(12,5))
plt.title("Monthly Average Temperature - New York")
plt.xlabel("Month")
plt.ylabel("Temperature (K)")
plt.show()

#weather frequency
desc_cols = [col for col in merged.columns if "_desc" in col]
merged[desc_cols].mode().iloc[0]

#wind speed
plt.figure(figsize=(14,5))
plt.plot(merged["datetime"], merged["New York_windspd"])
plt.title("Wind Speed Over Time - New York")
plt.ylabel("Wind Speed")
plt.show()

merged.to_csv("weather_final.csv", index=False)

from google.colab import files
files.download("weather_final.csv")

